if (wp && wp.components) {

    wp.components.BF_Repeater = require('./fields/repeater')
    wp.components.BF_Hr = require('./fields/hr')
    wp.components.BF_Info = require('./fields/info')
    wp.components.BF_Heading = require('./fields/heading')
    wp.components.BF_Select_Popup = require('./fields/select_popup')
    wp.components.BF_Icon_Select = require('./fields/icon_select')
    wp.components.BF_Ajax_Action = require('./fields/ajax_action')
    wp.components.BF_Ajax_Select = require('./fields/ajax_select')
    wp.components.BF_Background_Image = require('./fields/background_image')
    wp.components.BF_Code = require('./fields/code')
    wp.components.BF_Editor = require('./fields/editor')
    wp.components.BF_Image_Preview = require('./fields/‌image_preview')
    wp.components.BF_Image_Radio = require('./fields/‌image_radio')
    wp.components.BF_Image_Select = require('./fields/image_select')
    wp.components.BF_Media_Image = require('./fields/media_image')
    wp.components.BF_Slider = require('./fields/slider')
    wp.components.BF_Sorter_Checkbox = require('./fields/sorter_checkbox')
    wp.components.BF_Section_Container = require('./fields/bf_section_container')
    wp.components.BF_Switch = require('./fields/switch')
    wp.components.BF_Term_Select = require('./fields/term_select')
    wp.components.BF_Edit_Panel = require('./fields/bf_edit_panel')
}
